SET DATESTYLE = 'ISO,DMY';
SHOW DATESTYLE;

SET DATESTYLE='ISO,MDY';
SHOW DATESTYLE;

CREATE TABLE TEST_TIME(
STARTDATE DATE,
STARTSTAMP TIMESTAMP,
STARTTIME TIME
)

INSERT INTO TEST_TIME(STARTDATE,STARTSTAMP,STARTTIME)
VALUES(CURRENT_DATE,CURRENT_TIMESTAMP,CURRENT_TIME);

INSERT INTO TEST_TIME(STARTDATE,STARTSTAMP,STARTTIME)
VALUES(NOW::ABSTIME,TODAY::ABSTIME);

SELECT * FROM TEST_TIME;

SELECT * FROM PG_TIMEZONE_NAMES;

SELECT * FROM PG_TIMEZONE_ABBREVS;

ALTER TABLE TEST_TIME
ADD COLUMN ENDSTAMP TIMESTAMP WITH TIME ZONE;

ALTER TABLE TEST_TIME
ADD COLUMN ENDTIME TIME WITH TIME ZONE;

INSERT INTO TEST_TIME
(ENDSTAMP,ENDTIME)
VALUES('01/20/2018 10:30:00','10:30:00+5');

SELECT * FROM TEST_TIME;

SHOW TIMEZONE;


--INTERVAL DATATYPE
ALTER TABLE TEST_TIME
ADD COLUMN SPAN INTERVAL;

DELETE FROM TEST_TIME;

INSERT INTO TEST_TIME
(SPAN)
VALUES('5 DECADES 3 YEARS 6 MONTHS 3 DAYS');
INSERT INTO TEST_TIME
(SPAN)
VALUES('5 DECADES 3 YEARS 6 MONTHS 3 DAYS AGO');

SELECT * FROM TEST_TIME;

INSERT INTO TEST_TIME
(SPAN)
VALUES('4,32:12:10');

INSERT INTO TEST_TIME(SPAN)
VALUES('1-2');

--DATE ARITHMETIC

SELECT DATE '2018-09-28'+INTERVAL '5 DAYS 1 HOUR';
SELECT TIME '5:30:10'+INTERVAL '70 MINUTES 80 SECONDS';

SELECT AGE(TIMESTAMP '2025-10-03',TIMESTAMP '1999-10-03');

SELECT AGE(TIMESTAMP '1969-07-24');


--EXTRACT
SELECT EXTRACT(YEAR FROM AGE(BIRTHDATE)),FIRSTNAME,LASTNAME
FROM EMPLOYEES;

--DATE_PART
SELECT DATE_PART('DAY',SHIPPEDDATE)
FROM ORDERS;

SELECT HIREDATE::TIMESTAMP
FROM EMPLOYEES;

SELECT CAST(HIREDATE AS TIMESTAMP)
FROM EMPLOYEES;
