UPDATE friends
SET children[2:3]=ARRAY['Suzy','Billy']
WHERE (name).first_name = 'Boyd';

SELECT children
FROM friends
WHERE (name).first_name = 'Boyd'
LIMIT 1;

UPDATE salary_employees
SET pay_by_quarter=ARRAY[22000,25000,27000,22000]
WHERE name='Bill';

SELECT pay_by_quarter
FROM salary_employees
WHERE name='Bill';
/*DECLARING ARRAYS*/
DROP TABLE IF EXISTS FRIENDS;

CREATE TABLE FRIENDS(
NAME FULL_NAME,
ADDRESS ADDRESS,
SPEICALDATES DATES_TO_REMEMBR,
CHILDREN VARCHAR(50) ARRAY
)

CREATE TABLE SALARY_EMPLOYEES(
NAME TEXT,
PAY_BY_QUARTER INT[4],
SCHEDULE TEXT[][]
)

--INSERT VALUES INTO FRIENDS

INSERT INTO FRIENDS(NAME,ADDRESS,SPEICALDATES,CHILDREN)
VALUES(ROW('BOYD','M','GREGORY'),
	  ROW('7777','','BOISE','IDAHO','USA','55555'),
	  ROW('1969-02-01',49,'2001-02-01'),
	   '{"AUSTIN","ANA GRACE"}'
	  )
	  
INSERT INTO SALARY_EMPLOYEES(NAME,PAY_BY_QUARTER,SCHEDULE)
VALUES('BILL',
	  ARRAY[2000,2000,2000,2000],
	  ARRAY[['MEETING','TRAINING'],
			['LUNCH','SALES CALL']])
			
--ACCESSING ARRAYS

SELECT CHILDREN[2]
FROM FRIENDS;

SELECT PAY_BY_QUARTER[2:3]
FROM SALARY_EMPLOYEES;

SELECT ARRAY_DIMS(SCHEDULE)
FROM SALARY_EMPLOYEES;

UPDATE FRIENDS
SET CHILDREN=ARRAY['MADDLE','TMIMMY','CHERYL']
WHERE (NAME).FIRSTNAME='BOYD';


SELECT CHILDREN
FROM FRIENDS
WHERE (NAME).FIRSTNAME='BOYD';

UPDATE FRIENDS
SET CHILDREN[2]='RIKKY'
WHERE (NAME).FIRSTNAME='BOYD';



UPDATE salary_employees
SET pay_by_quarter[4]=26000
WHERE name='Bill';

SELECT pay_by_quarter
FROM salary_employees
WHERE name='Bill';

UPDATE salary_employees
SET pay_by_quarter[2:3]=ARRAY[24000,25000]
WHERE name='Bill';

SELECT pay_by_quarter
FROM salary_employees
WHERE name='Bill';
