 /*CREATING SEQUENCE*/
 
 CREATE SEQUENCE TEST_SEQUENCE;
 
 SELECT NEXTVAL('TEST_SEQUENCE');
 
 --SELECTING CURRENT VALUE OF SEQUENCE
 SELECT CURRVAL('TEST_SEQUENCE');
 
 SELECT LASTVAL();
 
 SELECT SETVAL('TEST_SEQUENCE',14);
 
 SELECT NEXTVAL('TEST_SEQUENCE');
 
 SELECT SETVAL('TEST_SEQUENCE',25,FALSE);
 
 SELECT NEXTVAL('TEST_SEQUENCE');
 
 
 --CREATE A SEQUENCE INCREMENTING BY 5
 CREATE SEQUENCE IF NOT EXISTS
 TEST_SEQUENCE2 INCREMENT 5;
 
 SELECT NEXTVAL('TEST_SEQUENCE2');
 
 CREATE SEQUENCE IF NOT EXISTS TEST_SEQUENCE3
 INCREMENT 50
 MINVALUE 350
 MAXVALUE 5000
 START WITH 550
 
 SELECT NEXTVAL('TEST_SEQUENCE3');
 
 --CREATE SEQUENCE NAMED TEST_SEQUENCE4 
 --THAT INCREMENT BY 7 AND STARTS AT 33
 
 CREATE SEQUENCE TEST_SEQUENCE4 
 INCREMENT 7
 MINVALUE 20
 MAXVALUE 500
 START WITH 33
 
 SELECT NEXTVAL('TEST_SEQUENCE4');
 
 SELECT MAX(EMPLOYEEID) FROM EMPLOYEES;
 
 CREATE SEQUENCE IF NOT EXISTS
 EMPLOYEE_EMPLOYEEID_SEQUENCE
 START WITH 10 OWNED BY EMPLOYEES.EMPLOYEEID;
 
 INSERT INTO EMPLOYEES(LASTNAME,FIRSTNAME,TITLE,REPORTSTO)
 VALUES('SMITH','JOHN','ASSISTANT',2);
 
 ALTER TABLE EMPLOYEES
 ALTER EMPLOYEEID SET DEFAULT
 NEXTVAL('EMPLOYEE_EMPLOYEEID_SEQUENCE');
 
 SELECT * FROM EMPLOYEES;
 
 INSERT INTO EMPLOYEES(LASTNAME,FIRSTNAME,TITLE,REPORTSTO)
 VALUES('DONE','JOHN','ASSISTANT',3)
 RETURNING EMPLOYEEID;
 
 --CREATING A SEQUENCE FOR ORDERS TABLE AND 
 --ATTACHING IT TO ORDERS TABLE
 SELECT MAX(ORDERID) FROM ORDERS;
 CREATE SEQUENCE IF NOT EXISTS
 ORDERS_ORDERID_SEQUENCE
 START WITH 11078
 
 ALTER TABLE ORDERS
 ALTER ORDERID SET DEFAULT
 NEXTVAL('ORDERS_ORDERID_SEQUENCE');
 
 INSERT INTO ORDERS(CUSTOMERID,EMPLOYEEID,REQUIREDDATE,SHIPPEDDATE)
 VALUES('VINET',5,'1996-07-02','1996-07-12');
 
 /*ALTER AND DELETE SEQUENCES*/
 ALTER SEQUENCE EMPLOYEE_EMPLOYEEID_SEQUENCE
 RESTART WITH 1000;
 
 SELECT NEXTVAL('EMPLOYEE_EMPLOYEEID_SEQUENCE');
 
 
 --ALTER SEQUENCE ORDERS_ORDERID_SEQUENCE
 --START WITH 200000
 ALTER SEQUENCE ORDERS_ORDERID_SEQUENCE
 RESTART WITH 200000;
 
 SELECT NEXTVAL('ORDERS_ORDERID_SEQUENCE');
 
 --CHANGE THE NAME OF SEQUENCE
 ALTER SEQUENCE TEST_SEQUENCE
 RENAME TO TEST_SEQUENCE1;
 
 ALTER SEQUENCE TEST_SEQUENCE4
 RENAME TO TEST_SEQUENCE_FOUR;
 
 --DROP SEQUENCE 
 DROP SEQUENCE TEST_SEQUENCE1;
 
 DROP SEQUENCE TEST_SEQUENCE_FOUR;
 
 
 --USING SERIAL
 CREATE TABLE EXES(
 EXID SERIAL,
NAME VARCHAR(255) 
 )
 
 INSERT INTO EXES(NAME)
 VALUES('MARTIN') RETURNING EXID;
 
 DROP TABLE IF EXISTS PETS;
 
 CREATE TABLE PETS(
 PETID SERIAL,
NAME VARCHAR(255)
 )
 
 INSERT INTO PETS(NAME)
 VALUES('COW') RETURNING PETID;
 